#
# Uses 'workflow_dispatch' type trigger to allow manual triggering of the workflow.
#

# Triggered:
#   - to run locally using 'act' util.
#   - to run on Github using the 'gh' CLI
#   - to run on Github using the Github UI 

# Display name
name: Manual Triggered Workflow with workflow_dispatch trigger

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  workflow_dispatch:
    # pass inputs to the workflow
    inputs:
      shark:
        description: "Name of your favorite plush Shark"
        required: true
        default: "Muffin"
        type: string
      quark:
        description: "What is your favorite quark?"
        required: true
        default: "Strange"
        type: choice
        options:
        - Up
        - Down
        - Truth
        - Beauty
        - Charm
        - Strange
      theway:
        description: "Do you know of the 8-fold way?"
        required: true
        type: boolean
        default: false
jobs:
  # This workflow contains a single job named hello-shark-quark
  greet:
    # cocntainer to use for the job
    runs-on: 
      - ubuntu-latest

    # finally, the stuff to do in the job
    steps:
    
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        echo "Hello ${{ github.event.inputs.shark }}" 
        echo "The ${{ github.event.inputs.quark }} Quark is my favorite quark too!"
    - name: Eight-fold way True
      if: github.event.inputs.theway == 'true'
      run: |
        echo "I know of the 8-fold way. Hail Gell-Mann!"
        echo "${{ github.event.inputs.theway }}"
    - name: Eight-fold way False
      if: github.event.inputs.theway == 'false'
      run: |
        echo "I know nothing of the 8-fold way."
        echo "${{ github.event.inputs.theway }}"