name: '06 - Use Pulumi Secrets' 
on:
  - workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  test-env-injection:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: 'actions/checkout@v4'
      - name: 'Authenticate with Pulumi Cloud'
        uses: 'pulumi/auth-actions@v1'
        with:
          organization: pulumi
          requested-token-type: urn:pulumi:token-type:access_token:organization
      - name: 'Install and inject ESC environment variables'
        uses: 'pulumi/esc-action@v1'
        with:
          environment: 'tinyco/someProject/myEnv@stable'
      - name: 'Verify environment variables'
        run: |
          echo "FOO=$FOO"
          echo "SOME_IMPORTANT_KEY=$SOME_IMPORTANT_KEY"
          echo "TEST_ENV=$TEST_ENV" 